### ISSUE TITLE
인공지능 학습 데이터 변경

### ISSUE THREAD

**Issue by Kyubin30** [Kyubin30/2022-2-industry-university-project#10]
인공지능 학습 데이터를 AI hub에서 가져오는데, 동영상 데이터가 아닌 사진 데이터라서 학습 과정을 변경하도록하겠습니다.

**Comment by Kyubin30** [comment]
https://aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=realm&dataSetSn=231

**Comment by jonghyunko** [comment]
제가 가져온 AI 모델 사진 기반이기 때문에 좋을 것 같습니다.

**Comment by Kyubin30** [comment]
팔굽혀펴기 데이터를 메인으로 제작하려 했는데, 제대로 인식이 되지 않아 관련 데이터셋 제작이 필요할 것 같습니다.

**Comment by Kyubin30** [comment]
![KakaoTalk_Photo_2022-12-04-17-45-53](https://user-images.githubusercontent.com/74997092/205481833-e7ee72d7-9aa0-46d7-a235-5ed8f72634f6.png)

**Comment by Kyubin30** [comment]
옵션 조정으로 해결 원래 데이터 사용해도 괜찮을 듯 함
