### ISSUE TITLE
peer review 관련해서 추가할 만한 것들 

### ISSUE THREAD

**Issue by jonghyunko** [Kyubin30/2022-2-industry-university-project#11]
peer review 받은 것들 중에 추가할 만한 것이 있는지 토의해 봅시다.

**Comment by jonghyunko** [comment]
웹 지원은 안하는 것으로 결정이 되었습니다.

**Comment by Kyubin30** [comment]
근피로도와 관련된 부분은 현재 추구하는 각도 및 인체 관절 포인트 좌표를 계산해 비교하는 프로젝트와 맞지 않는 것 같습니다.
