### ISSUE TITLE
mediapipe가 파이썬 3.11 버전에서는 지원하지 않음

### ISSUE THREAD

**Issue by junhoyoo00** [Kyubin30/2022-2-industry-university-project#18]
파이썬 버전을 가장 최신버전에서는 지원하지 않으므로 다운그레이드 할 필요성이 있음

**Comment by Kyubin30** [comment]
dependency에 추가하도록 하겠습니다.

**Comment by Kyubin30** [comment]
https://google.github.io/mediapipe/getting_started/troubleshooting.html#:~:text=after%20running%20pip%20install%20mediapipe%20usually%20indicates%20that%20there%20is%20no%20qualified%20MediaPipe%20Python%20for%20your%20system.%20Please%20note%20that%20MediaPipe%20Python%20PyPI%20officially%20supports%20the%2064%2Dbit%20version%20of%20Python%203.7%20to%203.10%20on%20the%20following%20OS%3A 관련 웹페이지 내용
