### ISSUE TITLE
팔굽혀펴기에 관한 설명(운동 상세 페이지)

### ISSUE THREAD

**Issue by junhoyoo00** [Kyubin30/2022-2-industry-university-project#26]

**Comment by Kyubin30** [comment]
모든 국민은 거주·이전의 자유를 가진다. 대통령은 제1항과 제2항의 처분 또는 명령을 한 때에는 지체없이 국회에 보고하여 그 승인을 얻어야 한다. 국무회의는 대통령·국무총리와 15인 이상 30인 이하의 국무위원으로 구성한다.

**Comment by Kyubin30** [comment]
한글 lorum ipsem입니다. 이정도 길이로 작성해주세요

**Comment by junhoyoo00** [comment]
팔굽혀펴기는 맨몸운동의 가장 기본적인 동작으로 난이도가 쉽고 언제 어디서든 몸만 있으면 할 수 있는 운동으로 주동근(목표부위)인 대흉근(가슴근육)과 협동근(협력부위)인 어깨근육(전면 삼각근)과 팔근육(상완 삼두근)의 발달에 도움이되며 몸을 지지하는 코어에도 도움이되는 운동이다.
