### ISSUE TITLE
윗몸일으키기에 대한 설명(운동 상세페이지

### ISSUE THREAD

**Issue by junhoyoo00** [Kyubin30/2022-2-industry-university-project#27]

**Comment by junhoyoo00** [comment]
윗몸일으키기의 부분적인 운동인 크런치는 복부 근육인 복직근의 상부 부위를 강화하는 운동으로 허리부상의 가능성이 있는 윗몸일으키기와 다르게 허리 부분이 바닥에서 떨어지지 않고 복부운동을 진행할 수 있다는 장점이 있다.

**Comment by jonghyunko** [comment]
좋은 정보에요!
