### ISSUE TITLE
로고 만들어 봤습니다

### ISSUE THREAD

**Issue by junhoyoo00** [Kyubin30/2022-2-industry-university-project#31]
![image](https://user-images.githubusercontent.com/74997095/206692059-f365ef79-338f-4c48-8048-400e3bf7e525.png)

**Comment by junhoyoo00** [comment]
평가 부탁드려요

**Comment by junhoyoo00** [comment]
![image](https://user-images.githubusercontent.com/74997095/206693383-cb5a0074-962a-4ca5-8ad0-e95d19ddea25.png)

**Comment by junhoyoo00** [comment]
![image](https://user-images.githubusercontent.com/74997095/206694985-ba85d4be-f94f-4211-8ca9-461f1c0999cc.png)

**Comment by jonghyunko** [comment]
마음에듭니다!

**Comment by Kyubin30** [comment]
바로 readme에 추가했습니다^^
