### ISSUE TITLE
feature_flask 머지

### ISSUE THREAD

**Issue by Kyubin30** [Kyubin30/2022-2-industry-university-project#35]
feature_flask_list와 feature_flask_streaming 브랜치를 feature_flask에 머지했습니다. 후에 feature_flask가 모두 완성 되면 마스터 브랜치에 머지하도록 하겠습니다.

**Comment by jonghyunko** [comment]
확인했습니다.

**Comment by junhoyoo00** [comment]
확인했습니다.
