### ISSUE TITLE
웹 앱 제작 기술 변경?

### ISSUE THREAD

**Issue by Kyubin30** [Kyubin30/2022-2-industry-university-project#4]
기존 웹 앱 제작 기술로 생각했던 안드로이드 스튜디오로 자바 개발을 좀 더 플라스크 친화, 범용성이 좋은 기술로 변경하고 싶음

**Comment by Kyubin30** [comment]
Flutter-크로스플랫폼 제작 가능, 플라스크 서버와 연동성이 더 간단해보임, UI가 안드로이드 스튜디오 자체 디자인보다 좋아보임

**Comment by jonghyunko** [comment]
내 생각에도 Flutter가 좀 더 나을 것 같음.

**Comment by Kyubin30** [comment]
기존 예상 기술인 안드로이드 스튜디오 웹뷰를 이용한 제작으로 결정
