### ISSUE TITLE
AI 모델 Flask에 적용 방법?

### ISSUE THREAD

**Issue by jonghyunko** [Kyubin30/2022-2-industry-university-project#9]
AI모델을 어떻게 Flask에 적용하는게 좋을까요?

**Comment by jonghyunko** [comment]
https://velog.io/@midoi327/PythonFlask-%ED%94%8C%EB%9D%BC%EC%8A%A4%ED%81%AC%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-%EB%94%A5%EB%9F%AC%EB%8B%9D-AI-%EB%AA%A8%EB%8D%B8-%EC%84%9C%EB%B9%99

이 블로그 방법대로 했는데 제대로 작동되지 않습니다.

**Comment by Kyubin30** [comment]
https://srgai.tistory.com/14 이 블로그 참고 바랍니다.

**Comment by Kyubin30** [comment]
flask 함수 내에서 파이썬 코드 입력한다면 적용될 것 같은데 확인바랍니다.

**Comment by jonghyunko** [comment]
404 오류가 떴지만 되는 것을 확인했습니다. 추가 인공지능 제작하면서 문제가 생기면 이슈에 또 올리겠습니다.
